name: emoy_pro_referral
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.6  
  provider: ^6.0.0
  intl: ^0.18.0 
  http: ^0.13.3
  flutter_secure_storage: ^9.2.2
  keycloak_flutter: ^0.0.21
  speech_to_text: ^7.0.0
  oauth2: ^2.0.1    
  connectivity_plus: ^2.3.0 
  logger: ^1.1.0  
  crypto: ^3.0.2  
  jwt_decode: ^0.3.0
  dart_jsonwebtoken: ^2.0.0
  url_launcher: ^6.1.9
  flutter_spinkit: ^5.2.1
  shared_preferences: ^2.2.0
  image: 4.5.2
  flutter_image_compress: ^2.1.0
  app_links: ^3.5.0 
  permission_handler: ^11.3.1
  flutter_custom_tabs: ^2.0.0
 
        

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/app_logo.png"
  remove_alpha_ios: true

flutter: 
  uses-material-design: true
  assets:
    - .env.dev
    - .env.prod
    - lib/assets/Goldimage.jpg
    - lib/assets/GoldCoin.jpg
    - lib/assets/placeholder.png

  fonts:
    - family: Inter_bold
      fonts:
        - asset: lib/assets/fonts/Quinlliyk.ttf
    - family: BAMINI
      fonts:
        - asset: lib/assets/fonts/sureshbo.ttf
    
